import pieces
import square

numPlayers = -1
player = ""
noPlayers = False
playerCount = 0
w_NumPieces = 16
b_NumPieces = 16
r_w_NumPieces = 1
r_b_NumPieces = 1
w_check = False
b_check = False
removed = False
removed_label = -1
removed_color = "none"
last_row = -1
last_col = -1
scanning = False
r_avail_Num = 1
p_w_Num = -1
p_b_Num = -1
m_f_ps = True
m_f_p_color = "none"
m_f_p_type = "none"
m_f_p_label = -1
m_f_row = -1
m_f_col = -1
m_t_ps = True
m_t_p_color = "none"
m_t_p_type = "none"
m_t_p_label = -1
m_t_row = -1
m_t_col = -1
m_fm = False
u_m_f_ps = True
u_m_f_p_color = "none"
u_m_f_p_type = "none"
u_m_f_p_label = -1
u_m_f_row = -1
u_m_f_col = -1
u_m_t_ps = True
u_m_t_p_color = "none"
u_m_t_p_type = "none"
u_m_t_p_label = -1
u_m_t_row = -1
u_m_t_col = -1
u_m_fm = False
no_b_king = False
no_w_king = False
firstPawnsNum = 1
checkmate = False
slow_speed = False
w_pieces = []
b_pieces = []
r_w_pieces = [pieces.Pawn("none", "none")]
r_b_pieces = [pieces.Pawn("none", "none")]
r_avail = [square.Square(False, "none", pieces.Pawn("none","none"), -1, -1)]
p_w_moves = []
p_b_moves = []
firstPawns = [pieces.Pawn("none", "none")]
